const PORTFOLIO = [
  {
    id: 'genshin',
    category: 'character',
    categoryLabel: '角色渲染',
    size: 'featured',
    title: '原神角色渲染',
    titleEn: 'Genshin Impact Character Rendering',
    desc: '逆向分析并复刻《原神》角色渲染管线，实现SDF面部阴影、多pass描边、各向异性头发、Ramp光照等效果。',
    cover: 'assets/images/genshin_front.png',
    primaryVideo: 'assets/videos/genshin_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/genshin_demo.mp4', label: '演示视频' },
      { type: 'image', src: 'assets/images/genshin_front.png', label: '正面' },
      { type: 'image', src: 'assets/images/genshin_noon.png', label: '中午暖光' },
      { type: 'image', src: 'assets/images/genshin_backlight.png', label: '背光' },
      { type: 'image', src: 'assets/images/genshin_night.png', label: '夜晚冷光' },
    ],
    webDemo: 'https://csdjk.github.io/LcLGenshinImpact/',
    links: [
      { label: 'Web Demo', url: 'https://csdjk.github.io/LcLGenshinImpact/', icon: 'globe' },
    ],
    tags: ['Unity', 'URP', 'HLSL', 'NPR', 'SDF阴影'],
    featured: true,
  },
  {
    id: 'hsr',
    category: 'character',
    categoryLabel: '角色渲染',
    size: 'featured',
    title: '崩坏·星穹铁道角色渲染',
    titleEn: 'Honkai Star Rail Character Rendering',
    desc: '逆向复刻《崩坏：星穹铁道》角色渲染，含镜流、黄泉、饮月等角色的金属、皮肤、头发材质及丰富后处理效果。',
    cover: 'assets/images/hsr_yinyue.png',
    primaryVideo: 'assets/videos/hsr_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/hsr_demo.mp4', label: '演示视频' },
      { type: 'image', src: 'assets/images/hsr_yinyue.png', label: '饮月' },
      { type: 'image', src: 'assets/images/hsr_jingliu.png', label: '镜流' },
      { type: 'image', src: 'assets/images/hsr_huangquan.png', label: '黄泉' },
      { type: 'image', src: 'assets/images/hsr_yinyue2.png', label: '饮月2' },
    ],
    webDemo: 'https://csdjk.github.io/LcLStarRail.github.io/',
    links: [
      { label: 'Bilibili', url: 'https://b23.tv/328Rom5', icon: 'video' },
      { label: 'Web Demo', url: 'https://csdjk.github.io/LcLStarRail.github.io/', icon: 'globe' },
      { label: '知乎分析', url: 'https://zhuanlan.zhihu.com/p/693831511', icon: 'article' },
    ],
    tags: ['Unity', 'URP', 'HLSL', 'NPR', '角色渲染'],
    featured: true,
  },
  {
    id: 'learnurp',
    category: 'effects',
    categoryLabel: '效果集',
    size: 'large',
    title: 'LearnURP 渲染效果集',
    titleEn: 'URP Rendering Effects Collection',
    desc: 'URP管线下实现SSR、SSPR、HBAO、TAA、OIT、体积光、毛发、雨水涟漪、VAT-RBD等17种渲染技术。',
    cover: 'assets/images/urp_ssr.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_ssr.gif', label: 'SSR' },
      { type: 'image', src: 'assets/images/urp_sspr.gif', label: 'SSPR' },
      { type: 'image', src: 'assets/images/urp_rain.gif', label: '雨效' },
      { type: 'image', src: 'assets/images/urp_cloud.gif', label: '模型云' },
      { type: 'image', src: 'assets/images/urp_vat.gif', label: 'VAT-RBD' },
      { type: 'image', src: 'assets/images/urp_ice2.gif', label: 'Ice' },
      { type: 'image', src: 'assets/images/urp_ice.png', label: 'Ice2' },
      { type: 'image', src: 'assets/images/urp_fur.png', label: '毛发' },
      { type: 'image', src: 'assets/images/urp_hbao.png', label: 'HBAO' },
      { type: 'image', src: 'assets/images/urp_taa.png', label: 'TAA' },
      { type: 'image', src: 'assets/images/urp_decal.png', label: 'Screen Decal' },
      { type: 'image', src: 'assets/images/urp_parallax.png', label: 'Parallax Mapping' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'SSR', 'SSPR', 'HBAO', 'TAA', 'OIT'],
  },
  {
    id: 'learnshader',
    category: 'effects',
    categoryLabel: '效果集',
    size: 'large',
    title: 'LearnUnityShader 材质集',
    titleEn: 'Unity Shader Learning (30+ effects)',
    desc: '30余种Shader效果学习记录，涵盖PBR、NPR卡通渲染、物理模拟（布料/绳索）、后处理、透明等完整分类。',
    cover: 'https://z3.ax1x.com/2021/09/23/4aB2X8.gif',
    gallery: [
      { type: 'image', src: 'https://z3.ax1x.com/2021/09/23/4aB2X8.gif', label: '布料模拟' },
      { type: 'image', src: 'https://z3.ax1x.com/2021/10/19/50Eeot.png', label: 'Custom PBR' },
      { type: 'image', src: 'https://s2.loli.net/2022/08/20/TsapkJdGrm346Iy.gif', label: 'Interior Mapping' },
      { type: 'image', src: 'https://z3.ax1x.com/2021/09/21/4JXjSK.png', label: 'Reflection/Refraction' },
      { type: 'image', src: 'https://s1.ax1x.com/2022/07/23/jX8DVx.png', label: 'Glass' },
      { type: 'image', src: 'https://i.loli.net/2021/09/25/ihgdEHMuLa5UvNz.gif', label: 'Energy Ball' },
      { type: 'image', src: 'https://i.loli.net/2021/09/30/JPqcE2fnxrKsVRT.gif', label: 'Cartoon Water' },
      { type: 'image', src: 'https://s2.loli.net/2023/03/27/kmGIL1z6lHZyASu.gif', label: 'Bezier Mesh' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'HLSL', 'PBR', 'NPR', '物理模拟'],
  },
  {
    id: 'water',
    category: 'effects',
    categoryLabel: '效果集',
    size: 'standard',
    title: '风格化水渲染',
    titleEn: 'Stylized Water Rendering',
    desc: '实现风格化水面着色，含法线扰动、深浅水色渐变、焦散、泡沫线、水下折射及动态交互。',
    cover: 'assets/images/water_1.png',
    primaryVideo: 'assets/videos/water_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/water_demo.mp4', label: '演示视频 1' },
      { type: 'video', src: 'assets/videos/water_demo2.mp4', label: '演示视频 2' },
      { type: 'image', src: 'assets/images/water_1.png', label: 'Water 1' },
      { type: 'image', src: 'assets/images/water_2.png', label: 'Water 2' },
      { type: 'image', src: 'assets/images/water_3.png', label: 'Water 3' },
      { type: 'image', src: 'assets/images/water_4.png', label: 'Water 4' },
      { type: 'image', src: 'assets/images/water_5.png', label: 'Water 5' },
    ],
    links: [],
    tags: ['URP', 'Water Shader', 'Stylized'],
  },
  {
    id: 'g136',
    category: 'production',
    categoryLabel: '游戏实践',
    size: 'video',
    title: 'G136 游戏材质实践',
    titleEn: 'In-Game Material Production',
    desc: '游戏项目实际落地的材质效果展示，含九霄龙吟武器特效、孔雀时装材质、金玉葫芦材质等制作录屏。',
    cover: null,
    gallery: [
      { type: 'video', src: 'assets/videos/g136_jiuxiao.mp4', label: '九霄龙吟' },
      { type: 'video', src: 'assets/videos/g136_kongque.mp4', label: '孔雀时装' },
      { type: 'video', src: 'assets/videos/g136_jinyuhu.mp4', label: '金玉葫芦' },
    ],
    links: [],
    tags: ['Game', 'Production', '武器', '时装'],
  },
  {
    id: 'softraster',
    category: 'graphics',
    categoryLabel: '图形学',
    size: 'standard',
    title: '软光栅化渲染器',
    titleEn: 'Software Rasterizer',
    desc: '基于Unity实现的自定义软光栅化渲染器，涵盖背面剔除、视锥裁剪、透视纠正插值、MSAA等核心图形算法。',
    cover: 'assets/images/softraster_1.png',
    gallery: [
      { type: 'image', src: 'assets/images/softraster_1.png', label: '渲染结果' },
      { type: 'image', src: 'assets/images/softraster_2.png', label: '线框模式' },
      { type: 'image', src: 'assets/images/softraster_3.png', label: '深度测试' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcL-Soft-Render', icon: 'github' },
    ],
    tags: ['C#', '光栅化', 'MSAA', '图形学基础'],
  },
  {
    id: 'houdini',
    category: 'tools',
    categoryLabel: '工具',
    size: 'standard',
    title: 'Houdini 工具集',
    titleEn: 'Custom Houdini HDA Library',
    desc: '封装常用Houdini HDA节点库，含地形处理、植被生成、RBD破碎动画等程序化工具，大幅提升内容制作效率。',
    cover: 'https://raw.githubusercontent.com/csdjk/LcLLib-for-Houdini/master/image/README/1693816134877.gif',
    gallery: [
      { type: 'image', src: 'https://raw.githubusercontent.com/csdjk/LcLLib-for-Houdini/master/image/README/1693816134877.gif', label: 'Houdini Tool 1' },
      { type: 'image', src: 'https://raw.githubusercontent.com/csdjk/LcLLib-for-Houdini/master/image/README/1693828818467.png', label: 'Houdini Tool 2' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcLLib-for-Houdini', icon: 'github' },
    ],
    tags: ['Houdini', 'HDA', 'VEX', 'Procedural'],
  },
  {
    id: 'unitytools',
    category: 'tools',
    categoryLabel: '工具',
    size: 'standard',
    title: 'Unity Editor 工具集',
    titleEn: 'Unity Editor Tools',
    desc: '自定义ShaderGUI扩展、Shader变体收集与剔除工具、LcLProfiler性能分析器等实用Editor扩展工具集。',
    cover: 'https://raw.githubusercontent.com/csdjk/LcL-Tools-Unity/master/image/README/ShaderGUI.gif',
    gallery: [
      { type: 'image', src: 'https://raw.githubusercontent.com/csdjk/LcL-Tools-Unity/master/image/README/ShaderGUI.gif', label: 'ShaderGUI' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcL-Tools-Unity', icon: 'github' },
    ],
    tags: ['Unity Editor', 'C#', 'ShaderGUI', 'Profiler'],
  },
];
