const PORTFOLIO = [
  {
    id: 'genshin',
    category: 'character',
    categoryLabel: '角色渲染',
    size: 'featured',
    title: '原神角色渲染',
    titleEn: 'Genshin Impact Character Rendering',
    desc: '逆向分析并复刻《原神》角色渲染管线，实现SDF面部阴影、多pass描边、各向异性头发、Ramp光照等效果。',
    cover: 'assets/images/genshin_front.png',
    primaryVideo: 'assets/videos/genshin_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/genshin_demo.mp4', label: '演示视频' },
      { type: 'image', src: 'assets/images/genshin_front.png', label: '正面' },
      { type: 'image', src: 'assets/images/genshin_noon.png', label: '中午暖光' },
      { type: 'image', src: 'assets/images/genshin_backlight.png', label: '背光' },
      { type: 'image', src: 'assets/images/genshin_night.png', label: '夜晚冷光' },
    ],
    webDemo: 'https://csdjk.github.io/LcLGenshinImpact/',
    links: [
      { label: 'Web Demo', url: 'https://csdjk.github.io/LcLGenshinImpact/', icon: 'globe' },
    ],
    tags: ['Unity', 'URP', 'HLSL', 'NPR', 'SDF阴影'],
    featured: true,
  },
  {
    id: 'hsr',
    category: 'character',
    categoryLabel: '角色渲染',
    size: 'featured',
    title: '崩坏·星穹铁道角色渲染',
    titleEn: 'Honkai Star Rail Character Rendering',
    desc: '逆向复刻《崩坏：星穹铁道》角色渲染，含镜流、黄泉、饮月等角色的金属、皮肤、头发材质及丰富后处理效果。',
    cover: 'assets/images/hsr_yinyue.png',
    primaryVideo: 'assets/videos/hsr_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/hsr_demo.mp4', label: '演示视频' },
      { type: 'image', src: 'assets/images/hsr_yinyue.png', label: '饮月' },
      { type: 'image', src: 'assets/images/hsr_jingliu.png', label: '镜流' },
      { type: 'image', src: 'assets/images/hsr_huangquan.png', label: '黄泉' },
      { type: 'image', src: 'assets/images/hsr_yinyue2.png', label: '饮月2' },
    ],
    webDemo: 'https://csdjk.github.io/LcLStarRail.github.io/',
    links: [
      { label: 'Bilibili', url: 'https://b23.tv/328Rom5', icon: 'video' },
      { label: 'Web Demo', url: 'https://csdjk.github.io/LcLStarRail.github.io/', icon: 'globe' },
      { label: '知乎分析', url: 'https://zhuanlan.zhihu.com/p/693831511', icon: 'article' },
    ],
    tags: ['Unity', 'URP', 'HLSL', 'NPR', '角色渲染'],
    featured: true,
  },

  // ─── LearnURP 效果集 (展开) ─────────────────────────────────
  {
    id: 'urp-ssr',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'SSR 屏幕空间反射',
    titleEn: 'Screen Space Reflection',
    desc: '基于屏幕空间的反射技术，通过深度图与法线图实时计算反射结果，适用于水面、湿润地面等场景。',
    cover: 'assets/images/urp_ssr.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_ssr.gif', label: 'SSR' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'SSR', '后处理'],
  },
  {
    id: 'urp-sspr',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'SSPR 平面反射',
    titleEn: 'Screen Space Planar Reflection',
    desc: '基于Compute Shader的屏幕空间平面反射，性能优于传统镜面相机方案，常用于水面/地面镜面反射。',
    cover: 'assets/images/urp_sspr.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_sspr.gif', label: 'SSPR' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'SSPR', 'Compute Shader'],
  },
  {
    id: 'urp-rain',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '雨水涟漪效果',
    titleEn: 'Rain Ripple Effect',
    desc: '基于FlowMap与法线扰动的雨水涟漪材质，模拟水面动态波纹与表面湿润反射，适配场景湿天氛围。',
    cover: 'assets/images/urp_rain.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_rain.gif', label: '雨效' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'FlowMap', '雨水'],
  },
  {
    id: 'urp-cloud',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '模型云',
    titleEn: 'Model-based Cloud',
    desc: '基于体积/Mesh模型的卡通风格云朵渲染，模拟次表面散射与边缘光，适合写实/二次元天空场景。',
    cover: 'assets/images/urp_cloud.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_cloud.gif', label: '模型云' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'Cloud', 'NPR'],
  },
  {
    id: 'urp-vat',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'VAT-RBD 顶点动画贴图',
    titleEn: 'Vertex Animation Texture (Rigid Body)',
    desc: '将Houdini RBD刚体破碎动画烘焙至贴图，运行时通过顶点采样还原动画，实现海量动态破碎而无需骨骼。',
    cover: 'assets/images/urp_vat.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_vat.gif', label: 'VAT-RBD' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'VAT', 'Houdini', 'RBD'],
  },
  {
    id: 'urp-ice',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '冰冻效果',
    titleEn: 'Ice Freezing Effect',
    desc: '动态冰冻覆盖效果，基于World Position与噪声渐变控制冰层生长，搭配菲涅尔与法线扰动表现冰晶质感。',
    cover: 'assets/images/urp_ice2.gif',
    gallery: [
      { type: 'image', src: 'assets/images/urp_ice2.gif', label: '冰冻动态' },
      { type: 'image', src: 'assets/images/urp_ice.png', label: '冰晶静态' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'Ice', 'Fresnel'],
  },
  {
    id: 'urp-fur',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '毛发渲染 Shell Fur',
    titleEn: 'Shell-based Fur Rendering',
    desc: '基于Shell层叠技术的毛发渲染方案，多Pass剥离毛皮层级，模拟真实毛发体积与各向异性高光。',
    cover: 'assets/images/urp_fur.png',
    gallery: [
      { type: 'image', src: 'assets/images/urp_fur.png', label: '毛发' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'Fur', 'Shell'],
  },
  {
    id: 'urp-hbao',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'HBAO 屏幕空间环境光遮蔽',
    titleEn: 'Horizon-Based Ambient Occlusion',
    desc: 'Horizon-Based AO实现屏幕空间环境光遮蔽，相比SSAO更精确还原物体接触阴影，提升画面层次感。',
    cover: 'assets/images/urp_hbao.png',
    gallery: [
      { type: 'image', src: 'assets/images/urp_hbao.png', label: 'HBAO' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'HBAO', '后处理'],
  },
  {
    id: 'urp-taa',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'TAA 时间抗锯齿',
    titleEn: 'Temporal Anti-Aliasing',
    desc: '基于历史帧重投影的时间抗锯齿方案，通过Jitter与速度缓冲消除锯齿，画面平滑稳定。',
    cover: 'assets/images/urp_taa.png',
    gallery: [
      { type: 'image', src: 'assets/images/urp_taa.png', label: 'TAA' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'TAA', '抗锯齿'],
  },
  {
    id: 'urp-decal',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'Screen Decal 屏幕贴花',
    titleEn: 'Screen Space Decal',
    desc: '基于深度重建的屏幕空间贴花系统，将弹孔、血迹、涂鸦等贴花精准投射到任意几何表面。',
    cover: 'assets/images/urp_decal.png',
    gallery: [
      { type: 'image', src: 'assets/images/urp_decal.png', label: 'Screen Decal' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'Decal', '深度重建'],
  },
  {
    id: 'urp-parallax',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'Parallax Mapping 视差映射',
    titleEn: 'Parallax Occlusion Mapping',
    desc: '通过高度图与视线步进迭代模拟表面凹凸感，相比法线贴图更具立体感，适用于砖墙/裂缝等纹理。',
    cover: 'assets/images/urp_parallax.png',
    gallery: [
      { type: 'image', src: 'assets/images/urp_parallax.png', label: 'Parallax Mapping' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnURP', icon: 'github' },
    ],
    tags: ['URP', 'Parallax', '高度图'],
  },

  // ─── LearnUnityShader 材质集 (展开) ─────────────────────────────
  {
    id: 'shader-cloth',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '布料物理模拟',
    titleEn: 'Cloth Physics Simulation',
    desc: '基于质点-弹簧模型的布料物理模拟，结合GPU计算并行求解约束，实时表现风力与碰撞响应。',
    cover: 'assets/images/shader_cloth.gif',
    gallery: [
      { type: 'image', src: 'assets/images/shader_cloth.gif', label: '布料模拟' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', '物理模拟', 'GPU'],
  },
  {
    id: 'shader-pbr',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'Custom PBR',
    titleEn: 'Custom Physically-Based Rendering',
    desc: '从零实现基于Cook-Torrance BRDF的物理着色，含GGX分布、Smith几何遮蔽、Fresnel-Schlick等核心公式。',
    cover: 'assets/images/shader_pbr.png',
    gallery: [
      { type: 'image', src: 'assets/images/shader_pbr.png', label: 'Custom PBR' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'PBR', 'BRDF'],
  },
  {
    id: 'shader-interior',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'Interior Mapping 室内映射',
    titleEn: 'Interior Mapping',
    desc: '通过Cube贴图与切线空间运算在单平面上模拟室内房间，无需建模即可营造大量楼宇内饰，性能极佳。',
    cover: 'assets/images/shader_interior.gif',
    gallery: [
      { type: 'image', src: 'assets/images/shader_interior.gif', label: 'Interior Mapping' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'Interior Mapping', '城市场景'],
  },
  {
    id: 'shader-reflection',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '反射与折射',
    titleEn: 'Reflection & Refraction',
    desc: '基于Cubemap与GrabPass的反射/折射效果，含Snell定律折射、菲涅尔混合，模拟玻璃球与水晶质感。',
    cover: 'assets/images/shader_reflection.png',
    gallery: [
      { type: 'image', src: 'assets/images/shader_reflection.png', label: 'Reflection/Refraction' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'Reflection', 'Refraction'],
  },
  {
    id: 'shader-glass',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '玻璃材质',
    titleEn: 'Stylized Glass',
    desc: '风格化玻璃Shader，含背景扭曲、菲涅尔边缘、双面渲染与高光叠加，适用于瓶罐/橱窗等场景物件。',
    cover: 'assets/images/shader_glass.png',
    gallery: [
      { type: 'image', src: 'assets/images/shader_glass.png', label: 'Glass' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'Glass', 'GrabPass'],
  },
  {
    id: 'shader-energyball',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '能量球特效',
    titleEn: 'Energy Ball VFX',
    desc: '科幻风格能量球Shader，结合菲涅尔轮廓光、噪声扰动UV、内部流动纹理，呈现脉动能量感。',
    cover: 'assets/images/shader_energyball.gif',
    gallery: [
      { type: 'image', src: 'assets/images/shader_energyball.gif', label: 'Energy Ball' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'VFX', '能量球'],
  },
  {
    id: 'shader-cartoonwater',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '卡通水面',
    titleEn: 'Cartoon Water Shader',
    desc: '风格化卡通水面材质，含程序化水波、深浅水色渐变、岸边泡沫线、涟漪扰动等NPR水面要素。',
    cover: 'assets/images/shader_cartoonwater.gif',
    gallery: [
      { type: 'image', src: 'assets/images/shader_cartoonwater.gif', label: 'Cartoon Water' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'NPR', 'Water'],
  },
  {
    id: 'shader-bezier',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: 'Bezier 曲线网格',
    titleEn: 'Bezier Curve Mesh',
    desc: '基于贝塞尔曲线的程序化Mesh生成，沿曲线挤出/扫掠几何，可用于绳索、轨道、流光等动态形态。',
    cover: 'assets/images/shader_bezier.gif',
    gallery: [
      { type: 'image', src: 'assets/images/shader_bezier.gif', label: 'Bezier Mesh' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LearnUnityShader', icon: 'github' },
    ],
    tags: ['Unity', 'Bezier', 'Procedural'],
  },

  // ─── 风格化水（保留） ──────────────────────────────────────
  {
    id: 'water',
    category: 'effects',
    categoryLabel: '材质效果',
    size: 'standard',
    title: '风格化水渲染',
    titleEn: 'Stylized Water Rendering',
    desc: '实现风格化水面着色，含法线扰动、深浅水色渐变、焦散、泡沫线、水下折射及动态交互。',
    cover: 'assets/images/water_1.png',
    primaryVideo: 'assets/videos/water_demo.mp4',
    gallery: [
      { type: 'video', src: 'assets/videos/water_demo.mp4', label: '演示视频 1' },
      { type: 'video', src: 'assets/videos/water_demo2.mp4', label: '演示视频 2' },
      { type: 'image', src: 'assets/images/water_1.png', label: 'Water 1' },
      { type: 'image', src: 'assets/images/water_2.png', label: 'Water 2' },
      { type: 'image', src: 'assets/images/water_3.png', label: 'Water 3' },
      { type: 'image', src: 'assets/images/water_4.png', label: 'Water 4' },
      { type: 'image', src: 'assets/images/water_5.png', label: 'Water 5' },
    ],
    links: [],
    tags: ['URP', 'Water Shader', 'Stylized'],
  },

  {
    id: 'g136',
    category: 'production',
    categoryLabel: '游戏实践',
    size: 'video',
    title: 'G136 游戏材质实践',
    titleEn: 'In-Game Material Production',
    desc: '游戏项目实际落地的材质效果展示，含九霄龙吟武器特效、孔雀时装材质、金玉葫芦材质等制作录屏。',
    cover: null,
    gallery: [
      { type: 'video', src: 'assets/videos/g136_jiuxiao.mp4', label: '九霄龙吟' },
      { type: 'video', src: 'assets/videos/g136_kongque.mp4', label: '孔雀时装' },
      { type: 'video', src: 'assets/videos/g136_jinyuhu.mp4', label: '金玉葫芦' },
    ],
    links: [],
    tags: ['Game', 'Production', '武器', '时装'],
  },
  {
    id: 'softraster',
    category: 'graphics',
    categoryLabel: '图形学',
    size: 'standard',
    title: '软光栅化渲染器',
    titleEn: 'Software Rasterizer',
    desc: '基于Unity实现的自定义软光栅化渲染器，涵盖背面剔除、视锥裁剪、透视纠正插值、MSAA等核心图形算法。',
    cover: 'assets/images/softraster_1.png',
    gallery: [
      { type: 'image', src: 'assets/images/softraster_1.png', label: '渲染结果' },
      { type: 'image', src: 'assets/images/softraster_2.png', label: '线框模式' },
      { type: 'image', src: 'assets/images/softraster_3.png', label: '深度测试' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcL-Soft-Render', icon: 'github' },
    ],
    tags: ['C#', '光栅化', 'MSAA', '图形学基础'],
  },
  {
    id: 'houdini',
    category: 'tools',
    categoryLabel: '工具',
    size: 'standard',
    title: 'Houdini 工具集',
    titleEn: 'Custom Houdini HDA Library',
    desc: '封装常用Houdini HDA节点库，含地形处理、植被生成、RBD破碎动画等程序化工具，大幅提升内容制作效率。',
    cover: 'assets/images/houdini_1.gif',
    gallery: [
      { type: 'image', src: 'assets/images/houdini_1.gif', label: 'Houdini Tool 1' },
      { type: 'image', src: 'assets/images/houdini_2.png', label: 'Houdini Tool 2' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcLLib-for-Houdini', icon: 'github' },
    ],
    tags: ['Houdini', 'HDA', 'VEX', 'Procedural'],
  },
  {
    id: 'unitytools',
    category: 'tools',
    categoryLabel: '工具',
    size: 'standard',
    title: 'Unity Editor 工具集',
    titleEn: 'Unity Editor Tools',
    desc: '自定义ShaderGUI扩展、Shader变体收集与剔除工具、LcLProfiler性能分析器等实用Editor扩展工具集。',
    cover: 'assets/images/unitytools_shadergui.png',
    gallery: [
      { type: 'image', src: 'assets/images/unitytools_shadergui.png', label: 'ShaderGUI' },
      { type: 'image', src: 'assets/images/unitytools_snap.gif', label: 'Snap Tools' },
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/csdjk/LcL-Tools-Unity', icon: 'github' },
    ],
    tags: ['Unity Editor', 'C#', 'ShaderGUI', 'Profiler'],
  },
];
